short/urls.py
from django.urls import path
from . import views

app_name = 'url'
urlpatterns = [
    path('', views.ShortUrlView.as_view(),name='short-url'),
    path('stats-export/<key>', views.StatsUrlExportView.as_view(),name='url-stats-export'),
    path('url/<key>', views.RedirectUrlView.as_view(),name='redirect-url'),
    path('url-check-password/<key>', views.RedirectPasswordCheckView.as_view(),name='redirect-url-password-check'),
    path('stats', views.StatsUrlView.as_view(),name='url-stats')
]

url_short/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('short.urls'))
]

short/models.py
from django.db import models

class Urls (models.Model):
    original_url = models.CharField(max_length=2083,db_index=True)
    url_key = models.CharField(max_length=50,unique=True,db_index=True)
    password = models.CharField(max_length=100,null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.original_url

class StatsUrl (models.Model):
    url_key = models.CharField(max_length=50,db_index=True)
    url = models.ForeignKey(Urls, on_delete=models.SET_NULL, null=True, related_name='stats')
    ip = models.CharField(max_length=30,db_index=True, null=True)
    hostname = models.CharField(max_length=100,null=True)
    city = models.CharField(max_length=50, db_index=True, null=True)
    region = models.CharField(max_length=50, db_index=True, null=True)
    country = models.CharField(max_length=50, db_index=True, null=True)
    latitude = models.CharField(max_length=50,null=True)
    longitude = models.CharField(max_length=50, null=True)
    org = models.CharField(max_length=50, null=True)
    timezone = models.CharField(max_length=50, db_index=True,null=True)
    country_name = models.CharField(max_length=50, db_index=True, null=True)
    browser = models.CharField(max_length=50, db_index=True,null=True)
    os = models.CharField(max_length=50, db_index=True,null=True)
    device = models.CharField(max_length=50, db_index=True,null=True)
    is_bot = models.BooleanField(null=True)
    is_email_client = models.BooleanField(null=True)
    is_pc = models.BooleanField(null=True)
    is_tablet = models.BooleanField(null=True)
    is_mobile = models.BooleanField(null=True)
    is_touch_capable = models.BooleanField(null=True)
    created_at = models.DateTimeField(auto_now_add=True,null=True)
    updated_at = models.DateTimeField(auto_now=True,null=True)

short/forms.py
from django import forms

class UrlShortForm(forms.Form):
    original_url = forms.CharField(required=True,label='Url',max_length=2083,error_messages={
        "required": "Your url must not be empty",
        "max_length": "Please enter a shorter url"
    })
    password = forms.CharField(required=False, label='Password',widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(UrlShortForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

short/views.py
from django.contrib.auth.hashers import check_password
from django.shortcuts import render, redirect
from django.views import View
from .forms import UrlShortForm
from .models import Urls, StatsUrl
from .services import short_url_service, url_stats_service
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import ListView
from django.urls import reverse


class ShortUrlView(View):
    def get(self, request):
        return render(request, 'short/index.html', {
            'url_short_form': UrlShortForm()
        })

    def post(self, request):
        url_short_form = UrlShortForm(request.POST)

        if url_short_form.is_valid():
            urls = short_url_service.make_short(url_short_form)
            return render(request, 'short/index.html', {
                'url_short_form': url_short_form,
                'urls': urls
            })

        return render(request, 'short/index.html', {
            'url_short_form': url_short_form
        })


class RedirectUrlView(View):
    def get(self, request, key):
        urls = get_object_or_404(Urls, url_key=key)
        if urls.password:
            return redirect('url:redirect-url-password-check', key=key)
        url_stats_service.save_stats(request, urls)
        return HttpResponseRedirect(urls.original_url)


class RedirectPasswordCheckView(View):
    def get(self, request, key):
        return render(request, 'short/url-password-check.html', {
            'url_key': key
        })

    def post(self, request, key):
        urls = get_object_or_404(Urls, url_key=key)
        if check_password(request.POST.get('password'),urls.password) is not True:
            return redirect('url:redirect-url-password-check', key=key)

        url_stats_service.save_stats(request, urls)
        return HttpResponseRedirect(urls.original_url)


class StatsUrlExportView(View):
    def post(self, request, key):
        return url_stats_service.export_stats(key)


class StatsUrlView(ListView):
    template_name = 'short/stats.html'
    model = StatsUrl
    paginate_by = 10
    context_object_name = 'url_stats'

    def get_queryset(self):
        base_query = super().get_queryset()
        data = base_query.filter(url_key=self.request.GET.get('url_key', None)).order_by('-id')
        return data

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['url_key'] = self.request.GET.get('url_key', '')
        return context

short/templates/short/index.html
{% extends 'base.html' %}

{% block page_title %}
    <h1>Short url</h1>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <div class="card card-primary">
                    <form action="{% url 'url:short-url' %}" method="POST">
                        {% csrf_token %}
                        <div class="card-body">
                            {% for field in url_short_form %}
                                <div class="form-group {% if not field.errors %} errors {% endif %}">
                                    {{ field.label_tag }}
                                    {{ field }}
                                    {{ field.errors }}
                                </div>
                            {% endfor %}
                            {% if urls %}
                                <div class="form-group col-md-3">
                                    <label for="url_key">Short Url:</label>
                                    <input type="text" name="url_key"
                                           value="{% url 'url:redirect-url' urls.url_key %}" class="form-control" disabled>
                                </div>
                                 <div class="form-group col-md-3">
                                    <label for="url_key">
                                        <a href="{% url 'url:url-stats' %}?url_key={{ urls.url_key }}">Statistic</a>
                                    </label>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="url_key">
                                        <a href="{% url 'url:redirect-url' urls.url_key %}">Redirect url</a>
                                    </label>
                                </div>
                            {% endif %}
                        </div>

                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Short</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- /.row -->
    </div>
{% endblock %}

short/templates/short/stats.html
{% extends 'base.html' %}

{% block page_title %}
    <h1>Statistic</h1>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <div class="card card-primary">
                    <form action="{% url 'url:url-stats' %}?url_key={{ url_key }}" method="GET">
                        <div class="card-body">
                            <div class="form-group col-md-3">
                                <label for="url_key">Url key:</label>
                                <input type="text" name="url_key"
                                       value="{{ url_key }}" class="form-control">
                            </div>
                        </div>

                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Show Stats</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Url stats</h3>
                        {% if url_key %}
                        <div class="card-tools">
                            <form action="{% url 'url:url-stats-export' url_key %}" method="POST">
                                {% csrf_token %}
                                <button class="btn btn-block btn-secondary">Export</button>
                            </form>
                        </div>
                        {% endif %}
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th style="width: 10px">#</th>
                                <th>Ip</th>
                                <th>Country/City</th>
                                <th>Location</th>
                                <th>Timezone</th>
                                <th>Browser</th>
                                <th>OS</th>
                                <th>Device</th>
                                <th>Is PC</th>
                                <th>Is Mobile</th>
                                <th>Is Tablet</th>
                                <th>Is Bot</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for url_stat in url_stats %}
                                <tr>
                                    <td>{{ url_stat.id }}</td>
                                    <td>{{ url_stat.ip }}</td>
                                    <td>{{ url_stat.country_name }} / {{ url_stat.city }}</td>
                                    <td>{{ url_stat.latitude }} / {{ url_stat.longitude }}</td>
                                    <td>{{ url_stat.timezone }}</td>
                                    <td>{{ url_stat.browser }}</td>
                                    <td>{{ url_stat.os }}</td>
                                    <td>{{ url_stat.device }}</td>
                                    <td>{{ url_stat.is_pc }}</td>
                                    <td>{{ url_stat.is_mobile }}</td>
                                    <td>{{ url_stat.is_tablet }}</td>
                                    <td>{{ url_stat.is_bot }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer clearfix">
                        <div class="pagination">
                            <span class="step-links">
                                {% if url_stats.has_previous %}
                                    <a href="?page=1">&laquo; first</a>
                                    <a href="?page={{ url_stats.previous_page_number }}">previous</a>
                                {% endif %}

                                <span class="current">
                                    Page {{ url_stats.number }} of {{ url_stats.paginator.num_pages }}.
                                </span>

                                {% if url_stats.has_next %}
                                    <a href="?page={{ url_stats.next_page_number }}">next</a>
                                    <a href="?page={{ url_stats.paginator.num_pages }}">last &raquo;</a>
                                {% endif %}
                            </span>
                        </div>
                    </div>
                </div>
                <div class="pagination">
                </div>

            </div>
        </div>
        <!-- /.row -->
    </div>
{% endblock %}

short/templates/short/url-password-check.html
{% extends 'base.html' %}

{% block page_title %}
    <h1>Url password check</h1>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <div class="card card-primary">
                    <form action="{% url 'url:redirect-url-password-check' url_key %}" method="POST">
                        {% csrf_token %}
                        <div class="card-body">
                            <div class="form-group col-md-3">
                                <label for="url_key">Password:</label>
                                <input type="password" name="password" class="form-control">
                            </div>
                        </div>

                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Redirect</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- /.row -->
    </div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %} | Url shorter</title>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="https://adminlte.io/themes/v3/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://adminlte.io/themes/v3/dist/css/adminlte.min.css">
</head>
<body class="hold-transition layout-top-nav">
<div class="wrapper">

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
        <div class="container">
            <a href="{% url 'url:short-url' %}" class="navbar-brand">
                <img src="{% static 'images/logo.jpg' %}" alt="Url shorter" class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">Url shorter</span>
            </a>

            <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse order-3" id="navbarCollapse">
                <!-- Left navbar links -->
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="{% url 'url:short-url' %}" class="nav-link">Short url</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'url:url-stats' %}" class="nav-link">Stats</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- /.navbar -->

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        {% block page_title %}{% endblock %}
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            {% block content %}{% endblock %}
        </div>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Main Footer -->
    <footer class="main-footer">
        <!-- To the right -->
        <div class="float-right d-none d-sm-inline">
            Anything you want
        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; 2021 <a href="https://www.notion.so/tmindiashvili/Hello-I-m-Tazo-ed1606b7b43d4b15a7888e92140264fe">Tazo</a>.</strong> All rights reserved.
    </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->


<script src="https://adminlte.io/themes/v3/plugins/jquery/jquery.min.js"></script>
<script src="https://adminlte.io/themes/v3/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="https://adminlte.io/themes/v3/dist/js/adminlte.min.js"></script>
<script src="https://adminlte.io/themes/v3/dist/js/demo.js"></script>
</body>
</html>